### ISSUE TITLE
Styles.json not found on 2.0.3

### ISSUE THREAD

**Issue by Immortalin** [OwenMelbz/babel-plugin-tailwind-rn#4]
```
Failed building JavaScript bundle.
Unable to resolve "./styles.json" from "node_modules/babel-plugin-tailwind-rn/dist/useTailwind.js"
```

**Comment by Immortalin** [comment]
Installing babel-plugin-tailwind-rn 2.0.1 fixed the issue

**Comment by Immortalin** [comment]
Also the example repo uses `TailwindProvider` instead of `useTailwind` like the README, might want to use the same keyword for both to avoid confusion.

**Comment by OwenMelbz** [comment]
Hi,

`styles.json` and `screens.json` get generated when the metro bundler runs babel.

Metro however aggressively caches bundled code for performance.

If you're using expo you can push `shift + r` in the terminal window thats running metro, this will clear the caches.

Then relaunch the app using `i` or `a` for example.

You should see the files appear in `node_modules/babel-plugin-tailwind-rn/dist/`

**Comment by Immortalin** [comment]
The issue goes away on 2.0.1, it seems to only happen on 2.0.3

**Comment by OwenMelbz** [comment]
@Immortalin that was most likely luck because when you changed your package.json it forced a cache clear, which regenerated the file.

2.0.1 contains some bugs, so would not recommend using it.

If you upgrade to 2.0.3 and follow the instructions it should be okay.
